import type { AuthConfig } from "./types";

export const config = {
	enableSignup: true,
	enableMagicLink: true,
	enableSocialLogin: true,
	enablePasskeys: true,
	enablePasswordLogin: true,
	enableTwoFactor: true,
	sessionCookieMaxAge: 60 * 60 * 24 * 30,
	users: {
		enableOnboarding: true,
	},
	// Households are Better Auth organizations (spec.md F1); the UI never says "organization".
	organizations: {
		enable: true,
		hideOrganization: true,
		enableUsersToCreateOrganizations: true,
		requireOrganization: true,
		// Every top-level route word (design.md §3.3), so a household slug never shadows a route.
		forbiddenOrganizationSlugs: [
			"b",
			"f",
			"letters",
			"settings",
			"admin",
			"onboarding",
			"new-organization",
			"choose-plan",
			"checkout-return",
			"organization-invitation",
			"login",
			"signup",
			"verify",
			"forgot-password",
			"reset-password",
			"api",
			"image-proxy",
			"begin",
			"claim",
			"close",
			// Legacy routes that redirect into a household (design.md §3.4).
			"activity",
			"browse",
			"interests",
			"matches",
			"messages",
			"preferences",
			"premium",
			"profile",
			"quiz",
			"shortlist",
			"viewers",
		],
	},
} as const satisfies AuthConfig;
