import type { BiodataStatus, CandidateRelation, PageLanguage, PhotoVisibility } from "../domain";
import type { BiodataProfileInsert, PartnerPreferenceInsert } from "../schema/postgres";

/**
 * The demo cast (spec.md §14). Deliberately multicultural: the product leads with South Asian
 * diaspora families and stays open to anyone. Every email ends in @demo.rishta.test.
 */

export const DEMO_EMAIL_DOMAIN = "demo.rishta.test";

export function demoEmail(key: string) {
	return `${key}@${DEMO_EMAIL_DOMAIN}`;
}

type PageSeed = Omit<
	BiodataProfileInsert,
	"organizationId" | "handle" | "userId" | "dateOfBirth" | "status" | "timeZone" | "id"
> & {
	timeZone: string;
	age: number;
	birthday: [month: number, day: number];
};

type PreferenceSeed = Omit<PartnerPreferenceInsert, "organizationId" | "userId" | "id">;

export interface CandidateSeed {
	key: string;
	accountName: string;
	slug: string;
	relation: CandidateRelation;
	status: BiodataStatus;
	/** Null for a page still awaiting its candidate's claim. */
	claimed: boolean;
	publishedDaysAgo: number;
	photos: PhotoVisibility[];
	premium?: "trialing" | "active";
	readIncognito?: boolean;
	familySeesIntroductions?: boolean;
	familyLanguage?: PageLanguage;
	page: PageSeed;
	preference: PreferenceSeed;
}

const COMPLETE = { completedAt: new Date(), quizComplete: true } as const;

function womanWants(overrides: Partial<PreferenceSeed> = {}): PreferenceSeed {
	return {
		seeking: "male",
		marriageTimeline: "1_year",
		relocation: "within_country",
		residencyRequirement: "open",
		valuesLooks: 3,
		valuesPersonality: 5,
		valuesFinancial: 4,
		ageMin: 27,
		ageMax: 37,
		religions: [],
		diet: [],
		maritalStatus: ["never_married", "divorced"],
		dealbreakers: ["timeline"],
		...COMPLETE,
		...overrides,
	};
}

function manWants(overrides: Partial<PreferenceSeed> = {}): PreferenceSeed {
	return {
		seeking: "female",
		marriageTimeline: "1_year",
		relocation: "open",
		residencyRequirement: "open",
		valuesLooks: 3,
		valuesPersonality: 6,
		valuesFinancial: 3,
		ageMin: 24,
		ageMax: 33,
		religions: [],
		diet: [],
		maritalStatus: ["never_married", "divorced", "widowed"],
		dealbreakers: ["timeline"],
		...COMPLETE,
		...overrides,
	};
}

export const CANDIDATES: CandidateSeed[] = [
	// ===== Women =====
	{
		key: "priya",
		accountName: "Priya Sharma",
		slug: "priya-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 40,
		photos: ["after_yes", "after_yes", "after_yes"],
		premium: "trialing",
		familySeesIntroductions: true,
		familyLanguage: "hi",
		page: {
			displayName: "Priya S.",
			fullName: "Priya Sharma",
			gender: "female",
			age: 29,
			birthday: [3, 14],
			height: 163,
			religion: "hindu",
			practice: "moderately",
			community: "Punjabi",
			motherTongue: "Punjabi",
			languages: ["Hindi", "English"],
			maritalStatus: "never_married",
			education: "professional",
			university: "Rutgers University (PharmD)",
			profession: "Pharmacist",
			employer: "RWJBarnabas Health",
			incomeRange: "100k_150k",
			familyType: "nuclear",
			familyValues: "moderate",
			fatherOccupation: "Runs a small accounting practice",
			motherOccupation: "Teaches Hindi at a weekend community school",
			siblings: "One younger brother, Kabir (26), an engineer",
			nativePlace: "Jalandhar, Punjab",
			aboutFamily:
				"We are four at home in Edison, with my nani visiting every winter. Sundays are for long lunches, and my parents still argue about whose dal is better.",
			diet: "veg",
			smoking: "never",
			drinking: "never",
			aboutMe:
				"I'm a pharmacist at a hospital in New Brunswick, and one day I want to open a small neighbourhood pharmacy where people are known by name. I run on weekend mornings, read Amrita Pritam in translation, and I am the person my friends call to decode a prescription.",
			lookingFor:
				"Someone kind and settled in himself, who takes family seriously without letting it decide everything. I hope to marry within a year and would like to stay on the East Coast.",
			createdBy: "self",
			location: "Edison, New Jersey",
			country: "US",
			timeZone: "America/New_York",
			residency: "citizen",
			birthTime: "06:40",
			birthPlace: "Jalandhar",
			manglik: "no",
			invocation: "shri_ganesh",
			pageLanguage: "en",
			verification: "email",
			isVerified: true,
			contactPhone: "+17325550142",
			familyContactName: "Sunita Sharma",
			familyContactPhone: "+17325550143",
		},
		preference: womanWants({
			marriageTimeline: "1_year",
			relocation: "within_country",
			ageMin: 28,
			ageMax: 36,
			religions: ["hindu", "sikh", "jain"],
			diet: ["veg", "eggetarian", "jain_veg"],
			maritalStatus: ["never_married", "divorced"],
			dealbreakers: ["timeline", "age", "marital_status"],
			valuesPersonality: 6,
			valuesFinancial: 4,
			valuesLooks: 2,
			languages: ["Punjabi", "Hindi"],
		}),
	},
	{
		key: "maria",
		accountName: "Maria Santos",
		slug: "maria-demo",
		relation: "self",
		status: "closed",
		claimed: true,
		publishedDaysAgo: 120,
		photos: ["after_note"],
		page: {
			displayName: "Maria S.",
			fullName: "Maria Clara Santos",
			gender: "female",
			age: 31,
			birthday: [7, 2],
			height: 166,
			religion: "christian",
			practice: "very",
			community: "Brazilian",
			motherTongue: "Portuguese",
			languages: ["English", "Spanish"],
			maritalStatus: "never_married",
			education: "masters",
			university: "University of Miami",
			profession: "School counsellor",
			fatherOccupation: "Owns a bakery in Coral Gables",
			motherOccupation: "Nurse",
			siblings: "Two older sisters, both married",
			nativePlace: "Belo Horizonte, Brazil",
			diet: "non_veg",
			aboutMe: "I counsel middle-schoolers in Miami and sing in my parish choir.",
			lookingFor: "A man of faith who wants a big, loud family table.",
			location: "Miami, Florida",
			country: "US",
			timeZone: "America/New_York",
			residency: "citizen",
			closedReason: "engaged",
			closingStory:
				"We met at a friend's wedding in Orlando the month after I joined, and his family came to ours for Christmas. We're getting married in May.",
		},
		preference: womanWants({ religions: ["christian"], marriageTimeline: "6_months" }),
	},
	{
		key: "yuki",
		accountName: "Yuki Tanaka",
		slug: "yuki-demo",
		relation: "self",
		status: "paused",
		claimed: true,
		publishedDaysAgo: 60,
		photos: ["everyone"],
		page: {
			displayName: "Yuki T.",
			fullName: "Yuki Tanaka",
			gender: "female",
			age: 30,
			birthday: [11, 21],
			height: 158,
			religion: "buddhist",
			community: "Japanese",
			motherTongue: "Japanese",
			languages: ["English"],
			maritalStatus: "never_married",
			education: "masters",
			university: "Stanford University",
			profession: "Product designer",
			fatherOccupation: "Retired train engineer",
			motherOccupation: "Tea ceremony teacher",
			siblings: "One younger sister in Osaka",
			nativePlace: "Kyoto, Japan",
			diet: "non_veg",
			aboutMe:
				"I design software for hospitals and spend weekends hiking the Marin headlands.",
			lookingFor: "Someone patient, curious and close to his parents.",
			location: "San Francisco, California",
			country: "US",
			timeZone: "America/Los_Angeles",
			residency: "permanent_resident",
		},
		preference: womanWants({ marriageTimeline: "2_years_plus" }),
	},
	{
		key: "fatima",
		accountName: "Fatima Ali",
		slug: "fatima-demo",
		relation: "daughter",
		status: "active",
		claimed: true,
		publishedDaysAgo: 30,
		photos: ["after_yes"],
		page: {
			displayName: "Fatima A.",
			fullName: "Fatima Abdi Ali",
			gender: "female",
			age: 27,
			birthday: [5, 9],
			height: 165,
			religion: "muslim",
			practice: "very",
			community: "Somali",
			motherTongue: "Somali",
			languages: ["English", "Arabic"],
			maritalStatus: "never_married",
			education: "bachelors",
			university: "University of Toronto",
			profession: "Civil engineer",
			fatherOccupation: "Imam and community interpreter",
			motherOccupation: "Runs a catering kitchen",
			siblings: "Three younger brothers",
			nativePlace: "Hargeisa, Somaliland",
			aboutFamily:
				"Our home in Scarborough is always full: cousins, neighbours and too much canjeero.",
			diet: "halal",
			aboutMe:
				"Fatima designs stormwater systems for the city of Toronto and volunteers teaching Qur'an to children on Saturdays. She is steady, funny and the one her brothers call for advice.",
			lookingFor:
				"A practising Muslim man who is gentle, hardworking and ready to marry within a year.",
			createdBy: "parent",
			location: "Toronto, Ontario",
			country: "CA",
			timeZone: "America/Toronto",
			residency: "citizen",
			invocation: "bismillah",
		},
		preference: womanWants({
			religions: ["muslim"],
			diet: ["halal"],
			dealbreakers: ["timeline", "religion"],
			relocation: "within_country",
		}),
	},
	{
		key: "amara",
		accountName: "Amara Okafor",
		slug: "amara-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 25,
		photos: ["after_note"],
		page: {
			displayName: "Amara O.",
			fullName: "Amara Chiamaka Okafor",
			gender: "female",
			age: 30,
			birthday: [9, 1],
			height: 170,
			religion: "christian",
			community: "Igbo",
			motherTongue: "Igbo",
			languages: ["English"],
			maritalStatus: "never_married",
			education: "phd",
			university: "UT Austin",
			profession: "Research chemist",
			fatherOccupation: "Retired professor of geology",
			motherOccupation: "Pharmacist",
			siblings: "An older brother in Lagos",
			nativePlace: "Enugu, Nigeria",
			diet: "non_veg",
			aboutMe: "I make better battery materials by day and jollof for friends on Fridays.",
			lookingFor: "A man who prays, laughs easily and wants children.",
			location: "Austin, Texas",
			country: "US",
			timeZone: "America/Chicago",
			residency: "citizen",
		},
		preference: womanWants({ religions: ["christian"] }),
	},
	{
		key: "sofia",
		accountName: "Sofia Martinez",
		slug: "sofia-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 12,
		photos: ["everyone"],
		page: {
			displayName: "Sofia M.",
			fullName: "Sofia Martinez",
			gender: "female",
			age: 28,
			birthday: [1, 30],
			height: 160,
			religion: "christian",
			community: "Mexican-American",
			motherTongue: "Spanish",
			languages: ["English"],
			maritalStatus: "never_married",
			education: "bachelors",
			university: "Loyola University Chicago",
			profession: "Public defender's investigator",
			fatherOccupation: "Carpenter",
			motherOccupation: "Parish secretary",
			siblings: "A twin brother",
			nativePlace: "Guadalajara, Mexico",
			diet: "non_veg",
			aboutMe: "I find the witnesses nobody else can, and I dance at every family wedding.",
			lookingFor: "Someone who wants marriage soon and loves a crowded kitchen.",
			location: "Chicago, Illinois",
			country: "US",
			timeZone: "America/Chicago",
			residency: "citizen",
		},
		preference: womanWants({ marriageTimeline: "6_months" }),
	},
	{
		key: "zainab",
		accountName: "Zainab Qureshi",
		slug: "zainab-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 9,
		photos: ["after_yes"],
		page: {
			displayName: "زینب ق",
			fullName: "زینب قریشی",
			gender: "female",
			age: 28,
			birthday: [4, 18],
			height: 162,
			religion: "muslim",
			practice: "moderately",
			community: "Punjabi",
			motherTongue: "Urdu",
			languages: ["English", "Punjabi"],
			maritalStatus: "never_married",
			education: "masters",
			university: "Northwestern University",
			profession: "ڈیٹا تجزیہ کار",
			fatherOccupation: "ریٹائرڈ بینکر",
			motherOccupation: "گھریلو خاتون",
			siblings: "دو بڑے بھائی",
			nativePlace: "لاہور، پنجاب",
			diet: "halal",
			aboutMe:
				"میں شکاگو میں ایک ہسپتال کے لیے ڈیٹا کا تجزیہ کرتی ہوں۔ مجھے اردو شاعری، لمبی سیر اور اپنی امی کے ہاتھ کی بریانی پسند ہے۔",
			lookingFor: "ایک سچا، مہربان اور خاندان سے محبت کرنے والا شخص۔",
			location: "Chicago, Illinois",
			country: "US",
			timeZone: "America/Chicago",
			residency: "citizen",
			invocation: "bismillah",
			pageLanguage: "ur",
		},
		preference: womanWants({ religions: ["muslim"], diet: ["halal"] }),
	},

	// ===== Men =====
	{
		key: "omar",
		accountName: "Omar Hassan",
		slug: "omar-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 45,
		photos: ["after_note", "after_yes"],
		page: {
			displayName: "Omar H.",
			fullName: "Omar Khaled Hassan",
			gender: "male",
			age: 31,
			birthday: [2, 11],
			height: 180,
			religion: "muslim",
			practice: "moderately",
			community: "Egyptian",
			motherTongue: "Arabic",
			languages: ["English"],
			maritalStatus: "never_married",
			education: "masters",
			university: "Johns Hopkins University",
			profession: "Software engineer",
			employer: "A healthcare start-up in Baltimore",
			incomeRange: "150k_plus",
			familyType: "nuclear",
			familyValues: "moderate",
			fatherOccupation: "Cardiologist",
			motherOccupation: "Arabic teacher",
			siblings: "One married sister in Cairo",
			nativePlace: "Alexandria, Egypt",
			diet: "halal",
			aboutMe:
				"I build scheduling software for clinics and coach a kids' football team on Saturdays. I cook my grandmother's molokhia badly and often.",
			lookingFor:
				"A warm, curious woman who wants to marry soon and doesn't mind a football-mad husband.",
			location: "Baltimore, Maryland",
			country: "US",
			timeZone: "America/New_York",
			residency: "citizen",
		},
		preference: manWants({ marriageTimeline: "6_months", ageMin: 25, ageMax: 32 }),
	},
	{
		key: "david",
		accountName: "David Cohen",
		slug: "david-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 70,
		photos: ["everyone"],
		page: {
			displayName: "David C.",
			fullName: "David Aaron Cohen",
			gender: "male",
			age: 33,
			birthday: [10, 5],
			height: 177,
			religion: "jewish",
			community: "Israeli-American",
			motherTongue: "English",
			languages: ["Hebrew"],
			maritalStatus: "divorced",
			hasChildren: false,
			education: "professional",
			university: "Columbia Law School",
			profession: "Tenants' rights lawyer",
			fatherOccupation: "Architect",
			motherOccupation: "Violinist",
			siblings: "A younger brother in Tel Aviv",
			nativePlace: "Haifa, Israel",
			diet: "non_veg",
			aboutMe: "I help families keep their homes in Brooklyn and make challah every Friday.",
			lookingFor: "A partner who values Shabbat dinners and long walks after them.",
			location: "New York, New York",
			country: "US",
			timeZone: "America/New_York",
			residency: "citizen",
		},
		preference: manWants({ ageMin: 27, ageMax: 36 }),
	},
	{
		key: "andrei",
		accountName: "Andrei Volkov",
		slug: "andrei-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 50,
		photos: ["after_note"],
		page: {
			displayName: "Andrei V.",
			fullName: "Andrei Sergeyevich Volkov",
			gender: "male",
			age: 32,
			birthday: [12, 12],
			height: 185,
			religion: "christian",
			community: "Russian",
			motherTongue: "Russian",
			languages: ["English"],
			maritalStatus: "never_married",
			education: "phd",
			university: "Imperial College London",
			profession: "Structural engineer",
			fatherOccupation: "Physicist",
			motherOccupation: "Piano teacher",
			nativePlace: "St Petersburg, Russia",
			diet: "non_veg",
			aboutMe: "I design bridges and swim in the Serpentine all year round.",
			lookingFor: "A thoughtful woman who likes long conversations and longer walks.",
			location: "London",
			country: "GB",
			timeZone: "Europe/London",
			residency: "work_visa",
		},
		preference: manWants(),
	},
	{
		key: "jin",
		accountName: "Jin Park",
		slug: "jin-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 80,
		photos: ["everyone"],
		page: {
			displayName: "Jin P.",
			fullName: "Park Jin-woo",
			gender: "male",
			age: 30,
			birthday: [8, 8],
			height: 176,
			religion: "christian",
			community: "Korean",
			motherTongue: "Korean",
			languages: ["English"],
			maritalStatus: "never_married",
			education: "bachelors",
			university: "UCLA",
			profession: "Film editor",
			fatherOccupation: "Runs a dry-cleaning business",
			motherOccupation: "Church deaconess",
			nativePlace: "Busan, South Korea",
			diet: "non_veg",
			aboutMe: "I split my time between Seoul and Los Angeles cutting documentaries.",
			lookingFor: "Someone who wants to build a life in two cities, at least for a while.",
			location: "Los Angeles, California",
			country: "US",
			timeZone: "America/Los_Angeles",
			residency: "permanent_resident",
		},
		preference: manWants({ marriageTimeline: "2_years_plus" }),
	},
	{
		key: "rahul",
		accountName: "Rahul Patel",
		slug: "rahul-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 35,
		photos: ["after_yes"],
		page: {
			displayName: "Rahul P.",
			fullName: "Rahul Nitin Patel",
			gender: "male",
			age: 31,
			birthday: [6, 19],
			height: 175,
			religion: "hindu",
			community: "Gujarati",
			motherTongue: "Gujarati",
			languages: ["Hindi", "English"],
			maritalStatus: "never_married",
			education: "masters",
			university: "University of Washington",
			profession: "Cloud architect",
			fatherOccupation: "Owns two motels in Tacoma",
			motherOccupation: "Manages the family business",
			siblings: "One younger sister at university",
			nativePlace: "Anand, Gujarat",
			diet: "veg",
			aboutMe: "I build data centres for a living and garba-dance badly every Navratri.",
			lookingFor: "A family-minded woman who would like to settle on the West Coast.",
			location: "Seattle, Washington",
			country: "US",
			timeZone: "America/Los_Angeles",
			residency: "citizen",
		},
		preference: manWants({ religions: ["hindu", "jain"], diet: ["veg", "jain_veg"] }),
	},
	{
		key: "arjun",
		accountName: "Arjun Mehta",
		slug: "arjun-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 20,
		photos: ["after_note", "after_yes"],
		page: {
			displayName: "Arjun M.",
			fullName: "Arjun Mehta",
			gender: "male",
			age: 32,
			birthday: [6, 2],
			height: 178,
			religion: "hindu",
			practice: "moderately",
			community: "Punjabi",
			motherTongue: "Punjabi",
			languages: ["Hindi", "English"],
			maritalStatus: "never_married",
			education: "professional",
			university: "McMaster University (MD)",
			profession: "Family physician",
			employer: "Scarborough Health Network",
			incomeRange: "150k_plus",
			familyType: "nuclear",
			familyValues: "moderate",
			fatherOccupation: "Retired civil engineer",
			motherOccupation: "Schoolteacher",
			siblings: "One sister, married, in Brampton",
			nativePlace: "Ludhiana, Punjab",
			aboutFamily:
				"My parents moved to Toronto in 1998. They still keep a vegetable garden big enough for the whole street.",
			diet: "veg",
			aboutMe:
				"I'm a family physician in Scarborough and the one who cooks on Sundays. I play tabla, not very well, and I read everything by Khushwant Singh.",
			lookingFor:
				"Hoping to marry within a year. I'd move to the US for the right person and her family.",
			location: "Toronto, Ontario",
			country: "CA",
			timeZone: "America/Toronto",
			residency: "citizen",
			verification: "email",
			isVerified: true,
		},
		preference: manWants({
			religions: ["hindu", "sikh"],
			diet: ["veg", "eggetarian"],
			relocation: "open",
		}),
	},
	{
		key: "nikhil",
		accountName: "Nikhil Rao",
		slug: "nikhil-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 28,
		photos: ["after_yes", "after_yes"],
		page: {
			displayName: "Nikhil R.",
			fullName: "Nikhil Venkata Rao",
			gender: "male",
			age: 31,
			birthday: [1, 17],
			height: 174,
			religion: "hindu",
			community: "Telugu",
			motherTongue: "Telugu",
			languages: ["Hindi", "English"],
			maritalStatus: "never_married",
			education: "masters",
			university: "UT Dallas",
			profession: "Semiconductor engineer",
			employer: "Texas Instruments",
			incomeRange: "150k_plus",
			familyType: "nuclear",
			familyValues: "moderate",
			fatherOccupation: "Retired bank manager",
			motherOccupation: "Carnatic music teacher",
			siblings: "An older brother in Hyderabad",
			nativePlace: "Vijayawada, Andhra Pradesh",
			diet: "eggetarian",
			aboutMe: "I design chips in Dallas, run half-marathons and make a serious pesarattu.",
			lookingFor:
				"Someone warm and direct, who would like her parents and mine to become friends.",
			location: "Dallas, Texas",
			country: "US",
			timeZone: "America/Chicago",
			residency: "citizen",
			contactPhone: "+12145550110",
			familyContactName: "Lakshmi Rao",
			familyContactPhone: "+12145550111",
		},
		preference: manWants({ religions: ["hindu"] }),
	},
	{
		key: "sameer",
		accountName: "Sameer Joshi",
		slug: "sameer-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 33,
		photos: ["after_yes"],
		page: {
			displayName: "Sameer J.",
			fullName: "Sameer Anil Joshi",
			gender: "male",
			age: 33,
			birthday: [9, 29],
			height: 181,
			religion: "hindu",
			community: "Marathi",
			motherTongue: "Marathi",
			languages: ["Hindi", "English"],
			maritalStatus: "never_married",
			education: "phd",
			university: "Rice University",
			profession: "Petroleum geologist",
			employer: "An energy company in Houston",
			fatherOccupation: "Retired professor of Sanskrit",
			motherOccupation: "Physician",
			siblings: "A younger sister in Pune",
			nativePlace: "Pune, Maharashtra",
			diet: "veg",
			aboutMe: "I read rocks for a living and Marathi theatre for fun.",
			lookingFor: "A partner who likes quiet evenings as much as big festivals.",
			location: "Houston, Texas",
			country: "US",
			timeZone: "America/Chicago",
			residency: "citizen",
			contactPhone: "+17135550122",
		},
		preference: manWants({ religions: ["hindu"] }),
	},
	{
		key: "harpreet",
		accountName: "Harpreet Singh Gill",
		slug: "harpreet-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 18,
		photos: ["after_yes", "after_yes"],
		page: {
			displayName: "Harpreet S.",
			fullName: "Harpreet Singh Gill",
			gender: "male",
			age: 30,
			birthday: [4, 13],
			height: 183,
			religion: "sikh",
			practice: "very",
			community: "Punjabi",
			motherTongue: "Punjabi",
			languages: ["Hindi", "English"],
			maritalStatus: "never_married",
			education: "bachelors",
			university: "Toronto Metropolitan University",
			profession: "Electrical contractor",
			employer: "Gill Electric (family business)",
			familyType: "joint",
			familyValues: "traditional",
			fatherOccupation: "Founded the family electrical business",
			motherOccupation: "Runs the langar rota at our gurdwara",
			siblings: "Two younger brothers in the business",
			nativePlace: "Moga, Punjab",
			diet: "veg",
			aboutMe:
				"I run the family electrical business with my brothers and do seva at the gurdwara on Sundays.",
			lookingFor:
				"A woman who values faith and family, and would like a big joint household.",
			location: "Brampton, Ontario",
			country: "CA",
			timeZone: "America/Toronto",
			residency: "citizen",
			invocation: "ik_onkar",
		},
		preference: manWants({ religions: ["sikh", "hindu"], diet: ["veg"], relocation: "open" }),
	},
	{
		key: "dev",
		accountName: "Dev Shah",
		slug: "dev-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 15,
		photos: ["after_note"],
		page: {
			displayName: "Dev S.",
			fullName: "Dev Shah",
			gender: "male",
			age: 29,
			birthday: [11, 3],
			height: 172,
			religion: "jain",
			practice: "moderately",
			community: "Gujarati",
			motherTongue: "Gujarati",
			languages: ["Hindi", "English"],
			maritalStatus: "never_married",
			education: "masters",
			university: "NYU Stern",
			profession: "Actuary",
			fatherOccupation: "Diamond trader",
			motherOccupation: "Interior designer",
			siblings: "One older sister, married",
			nativePlace: "Surat, Gujarat",
			diet: "jain_veg",
			aboutMe:
				"I price risk for an insurer and volunteer at the Jain centre's Sunday school.",
			lookingFor: "Someone who shares a vegetarian kitchen and a sense of humour.",
			location: "Jersey City, New Jersey",
			country: "US",
			timeZone: "America/New_York",
			residency: "citizen",
		},
		preference: manWants({ diet: ["veg", "jain_veg"], relocation: "within_country" }),
	},
	{
		key: "vikram",
		accountName: "Vikram Iyer",
		slug: "vikram-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 26,
		photos: ["after_yes"],
		page: {
			displayName: "Vikram I.",
			fullName: "Vikram Subramanian Iyer",
			gender: "male",
			age: 32,
			birthday: [3, 3],
			height: 173,
			religion: "hindu",
			community: "Tamil",
			motherTongue: "Tamil",
			languages: ["Hindi", "English"],
			maritalStatus: "never_married",
			education: "masters",
			university: "University of Chicago",
			profession: "Economist at the Federal Reserve",
			fatherOccupation: "Retired chartered accountant",
			motherOccupation: "Bharatanatyam teacher",
			siblings: "A younger brother in Chennai",
			nativePlace: "Chennai, Tamil Nadu",
			diet: "veg",
			aboutMe: "I study inflation for a living and South Indian filter coffee for pleasure.",
			lookingFor: "A curious woman who likes books, music and her family.",
			location: "Chicago, Illinois",
			country: "US",
			timeZone: "America/Chicago",
			residency: "citizen",
		},
		preference: manWants({ religions: ["hindu"], relocation: "within_country" }),
	},
	{
		key: "karan",
		accountName: "Karan Bhatia",
		slug: "karan-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 4,
		photos: ["everyone"],
		page: {
			displayName: "Karan B.",
			fullName: "Karan Bhatia",
			gender: "male",
			age: 34,
			birthday: [7, 27],
			height: 179,
			religion: "hindu",
			community: "Punjabi",
			motherTongue: "Punjabi",
			languages: ["Hindi", "English"],
			maritalStatus: "never_married",
			education: "masters",
			profession: "Investment consultant",
			nativePlace: "Amritsar, Punjab",
			diet: "non_veg",
			aboutMe: "Consultant in London. Looking to settle down soon.",
			lookingFor: "A serious woman who is ready to marry quickly.",
			location: "London",
			country: "GB",
			timeZone: "Europe/London",
			residency: "other",
		},
		preference: manWants({ marriageTimeline: "6_months", ageMax: 32 }),
	},
	{
		key: "rohan",
		accountName: "Rohan Kapoor",
		slug: "rohan-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 10,
		photos: ["after_note", "after_yes"],
		page: {
			displayName: "Rohan K.",
			fullName: "Rohan Kapoor",
			gender: "male",
			age: 31,
			birthday: [10, 22],
			height: 180,
			religion: "hindu",
			practice: "moderately",
			community: "Punjabi",
			motherTongue: "Punjabi",
			languages: ["Hindi", "English"],
			maritalStatus: "never_married",
			education: "masters",
			university: "Columbia University",
			profession: "Urban planner",
			employer: "NYC Department of City Planning",
			familyType: "nuclear",
			familyValues: "moderate",
			fatherOccupation: "Retired airline pilot",
			motherOccupation: "Runs a Punjabi cooking school",
			siblings: "One older brother, married, in New Jersey",
			nativePlace: "Amritsar, Punjab",
			aboutFamily:
				"My parents live in Queens and are thinking about moving closer to my brother in New Jersey when they retire.",
			diet: "veg",
			aboutMe:
				"I plan bike lanes and parks for New York City, and I'm happiest at a crowded Sunday market. My mother taught half of Queens to make sarson da saag.",
			lookingFor:
				"Someone who wants to marry within a year and build a home close to both families.",
			location: "New York, New York",
			country: "US",
			timeZone: "America/New_York",
			residency: "citizen",
			verification: "email",
			isVerified: true,
		},
		preference: manWants({ religions: ["hindu", "sikh"], relocation: "within_country" }),
	},
	{
		key: "aditya",
		accountName: "Aditya Menon",
		slug: "aditya-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 14,
		photos: ["after_yes"],
		readIncognito: true,
		page: {
			displayName: "Aditya M.",
			fullName: "Aditya Menon",
			gender: "male",
			age: 30,
			birthday: [8, 14],
			height: 176,
			religion: "hindu",
			community: "Malayali",
			motherTongue: "Malayalam",
			languages: ["English", "Hindi"],
			maritalStatus: "never_married",
			education: "phd",
			university: "MIT",
			profession: "Robotics researcher",
			fatherOccupation: "Retired naval officer",
			motherOccupation: "Botanist",
			siblings: "A younger sister in Kochi",
			nativePlace: "Thrissur, Kerala",
			diet: "eggetarian",
			aboutMe:
				"I teach robots to pick fruit gently and spend weekends on the Charles in a kayak.",
			lookingFor:
				"Someone kind and adventurous, who would like to live near the ocean one day.",
			location: "Boston, Massachusetts",
			country: "US",
			timeZone: "America/New_York",
			residency: "citizen",
		},
		preference: manWants({ relocation: "within_country" }),
	},
	{
		key: "hamza",
		accountName: "Hamza Siddiqui",
		slug: "hamza-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 8,
		photos: ["after_yes"],
		page: {
			displayName: "حمزہ ص",
			fullName: "حمزہ صدیقی",
			gender: "male",
			age: 31,
			birthday: [12, 1],
			height: 178,
			religion: "muslim",
			practice: "moderately",
			community: "Hyderabadi",
			motherTongue: "Urdu",
			languages: ["English", "Hindi"],
			maritalStatus: "never_married",
			education: "masters",
			university: "University of Illinois Chicago",
			profession: "سافٹ ویئر انجینئر",
			fatherOccupation: "ریٹائرڈ پروفیسر",
			motherOccupation: "اسکول کی پرنسپل",
			siblings: "ایک بہن، شادی شدہ",
			nativePlace: "حیدرآباد، دکن",
			diet: "halal",
			aboutMe:
				"میں شکاگو میں سافٹ ویئر انجینئر ہوں۔ فارغ وقت میں غالب پڑھتا ہوں اور دوستوں کے لیے حیدرآبادی بریانی بناتا ہوں۔",
			lookingFor: "ایک پڑھی لکھی، خوش مزاج اور خاندان کی قدر کرنے والی شریکِ حیات۔",
			location: "Chicago, Illinois",
			country: "US",
			timeZone: "America/Chicago",
			residency: "citizen",
			invocation: "bismillah",
			pageLanguage: "ur",
		},
		preference: manWants({ relocation: "within_country" }),
	},
	{
		key: "manpreet",
		accountName: "Manpreet Singh Sandhu",
		slug: "manpreet-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 22,
		photos: ["after_yes"],
		page: {
			displayName: "Manpreet S.",
			fullName: "Manpreet Singh Sandhu",
			gender: "male",
			age: 32,
			birthday: [2, 28],
			height: 184,
			religion: "sikh",
			community: "Punjabi",
			motherTongue: "Punjabi",
			languages: ["English"],
			maritalStatus: "never_married",
			education: "bachelors",
			university: "University of British Columbia",
			profession: "Blueberry farmer and agronomist",
			fatherOccupation: "Farmer",
			motherOccupation: "Farmer",
			siblings: "An older sister in Surrey",
			nativePlace: "Jalandhar, Punjab",
			diet: "veg",
			aboutMe:
				"I run our family farm in the Fraser Valley and would not move from it for anything.",
			lookingFor: "Someone who would love a farm life near Vancouver.",
			location: "Vancouver, British Columbia",
			country: "CA",
			timeZone: "America/Vancouver",
			residency: "citizen",
		},
		preference: manWants({ relocation: "not_open" }),
	},
	{
		key: "siddharth",
		accountName: "Siddharth Bose",
		slug: "siddharth-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 6,
		photos: ["after_yes"],
		page: {
			displayName: "সিদ্ধার্থ ব",
			fullName: "সিদ্ধার্থ বসু",
			gender: "male",
			age: 30,
			birthday: [5, 25],
			height: 175,
			religion: "hindu",
			community: "Bengali",
			motherTongue: "Bengali",
			languages: ["English", "Hindi"],
			maritalStatus: "never_married",
			education: "phd",
			university: "University of Pennsylvania",
			profession: "স্নায়ুবিজ্ঞানী",
			fatherOccupation: "অবসরপ্রাপ্ত অধ্যাপক",
			motherOccupation: "গায়িকা",
			siblings: "এক ছোট বোন",
			nativePlace: "কলকাতা, পশ্চিমবঙ্গ",
			diet: "non_veg",
			aboutMe:
				"আমি ফিলাডেলফিয়ায় স্নায়ুবিজ্ঞান নিয়ে গবেষণা করি। রবীন্দ্রসংগীত, মাছের ঝোল আর দীর্ঘ আড্ডা আমার খুব প্রিয়।",
			lookingFor: "একজন সহৃদয়, কৌতূহলী মানুষ, যিনি পরিবারকে ভালোবাসেন।",
			location: "Philadelphia, Pennsylvania",
			country: "US",
			timeZone: "America/New_York",
			residency: "citizen",
			pageLanguage: "bn",
		},
		preference: manWants({ relocation: "within_country" }),
	},
	{
		key: "ishaan",
		accountName: "Ishaan Verma",
		slug: "ishaan-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 11,
		photos: ["after_yes"],
		page: {
			displayName: "Ishaan V.",
			fullName: "Ishaan Verma",
			gender: "male",
			age: 29,
			birthday: [7, 7],
			height: 177,
			religion: "hindu",
			community: "UP",
			motherTongue: "Hindi",
			languages: ["English"],
			maritalStatus: "never_married",
			education: "masters",
			university: "Northwestern University",
			profession: "Management consultant",
			fatherOccupation: "IAS officer (retired)",
			motherOccupation: "Gynaecologist",
			siblings: "An older brother in Delhi",
			nativePlace: "Lucknow, Uttar Pradesh",
			diet: "eggetarian",
			aboutMe: "I travel for work four days a week and cook Awadhi food on the fifth.",
			lookingFor: "Someone who will forgive the travel and enjoy the kebabs.",
			location: "Chicago, Illinois",
			country: "US",
			timeZone: "America/Chicago",
			residency: "citizen",
		},
		preference: manWants({ relocation: "within_country" }),
	},
	{
		key: "tejas",
		accountName: "Tejas Kulkarni",
		slug: "tejas-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 16,
		photos: ["after_yes"],
		page: {
			displayName: "Tejas K.",
			fullName: "Tejas Kulkarni",
			gender: "male",
			age: 30,
			birthday: [10, 30],
			height: 174,
			religion: "hindu",
			community: "Marathi",
			motherTongue: "Marathi",
			languages: ["Hindi", "English"],
			maritalStatus: "never_married",
			education: "masters",
			university: "IIT Bombay",
			profession: "Machine-learning engineer",
			fatherOccupation: "Runs a printing press",
			motherOccupation: "High-school principal",
			siblings: "No siblings",
			nativePlace: "Pune, Maharashtra",
			diet: "veg",
			aboutMe:
				"I'm moving to New Jersey next spring for work and would love to start a family there.",
			lookingFor: "A woman in the New York area, ideally vegetarian, close to her family.",
			location: "Pune, Maharashtra",
			country: "IN",
			timeZone: "Asia/Kolkata",
			residency: "work_visa",
		},
		preference: manWants({ relocation: "open" }),
	},
	{
		key: "neel",
		accountName: "Neel Desai",
		slug: "neel-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 60,
		photos: ["after_yes"],
		page: {
			displayName: "Neel D.",
			fullName: "Neel Desai",
			gender: "male",
			age: 31,
			birthday: [1, 5],
			height: 171,
			religion: "jain",
			community: "Gujarati",
			motherTongue: "Gujarati",
			languages: ["Hindi", "English"],
			maritalStatus: "never_married",
			education: "bachelors",
			profession: "Pharmacist",
			fatherOccupation: "Jeweller",
			motherOccupation: "Homemaker",
			nativePlace: "Ahmedabad, Gujarat",
			diet: "jain_veg",
			aboutMe: "Pharmacist in Edison who knows every good thali place in Middlesex County.",
			lookingFor: "A Jain or Hindu vegetarian woman in New Jersey.",
			location: "Edison, New Jersey",
			country: "US",
			timeZone: "America/New_York",
			residency: "citizen",
		},
		preference: manWants({ diet: ["veg", "jain_veg"], relocation: "within_country" }),
	},
	{
		key: "kunal",
		accountName: "Kunal Arora",
		slug: "kunal-demo",
		relation: "self",
		status: "active",
		claimed: true,
		publishedDaysAgo: 30,
		photos: ["everyone"],
		page: {
			displayName: "Kunal A.",
			fullName: "Kunal Arora",
			gender: "male",
			age: 33,
			birthday: [3, 30],
			height: 176,
			religion: "hindu",
			community: "Punjabi",
			motherTongue: "Punjabi",
			languages: ["Hindi", "English"],
			maritalStatus: "never_married",
			education: "bachelors",
			profession: "Car-dealership manager",
			nativePlace: "Delhi",
			diet: "non_veg",
			aboutMe: "Newark born and raised.",
			lookingFor: "A Punjabi girl.",
			location: "Newark, New Jersey",
			country: "US",
			timeZone: "America/New_York",
			residency: "citizen",
		},
		preference: manWants(),
	},
	{
		key: "ali",
		accountName: "Ali Khan",
		slug: "ali-demo",
		relation: "son",
		status: "awaiting_claim",
		claimed: false,
		publishedDaysAgo: 0,
		photos: [],
		page: {
			displayName: "Ali K.",
			gender: "male",
			age: 29,
			birthday: [9, 9],
			height: 178,
			religion: "muslim",
			community: "Pakistani",
			motherTongue: "Urdu",
			languages: ["English", "Punjabi"],
			maritalStatus: "never_married",
			education: "bachelors",
			university: "UT Arlington",
			profession: "Pharmacist",
			fatherOccupation: "Owns a grocery store in Irving",
			motherOccupation: "Homemaker",
			siblings: "Two younger sisters",
			nativePlace: "Lahore, Punjab",
			diet: "halal",
			aboutMe:
				"Ali is a pharmacist in Dallas, a patient older brother and the family's designated driver to every wedding.",
			lookingFor:
				"A practising Muslim girl from a warm family, ready to marry in the next year.",
			createdBy: "parent",
			location: "Dallas, Texas",
			country: "US",
			timeZone: "America/Chicago",
			residency: "citizen",
		},
		preference: manWants({
			religions: ["muslim"],
			completedAt: null,
			quizComplete: false,
		}),
	},
];

/** Accounts that help a household but are not candidates themselves. */
export const HELPERS = [
	{ key: "sunita", name: "Sunita Sharma", household: "priya", role: "admin", label: "Ammi" },
	{ key: "kabir", name: "Kabir Sharma", household: "priya", role: "member", label: "Bhaiya" },
	{ key: "nasreen", name: "Nasreen Khan", household: "ali", role: "owner", label: "Ammi" },
	{ key: "abdi", name: "Abdi Ali", household: "fatima", role: "admin", label: "Aabo" },
] as const;

export const ADMIN = { key: "admin", name: "Rishta Moderator" } as const;
