/**
 * The sample page on the founders' letter (design.md §15): one invented biodata, written by hand
 * in each script families read. Nothing here is generated at runtime. The labels match the
 * family link bundles (packages/i18n/translations/family/*.json) so the sample reads exactly
 * like a real page in that language.
 *
 * Arjun Mehta is not a real person, and the sample says so on the page.
 */

export const SAMPLE_LANGUAGES = ["en", "hi", "ur", "pa", "gu", "bn", "ta", "te"] as const;
export type SampleLanguage = (typeof SAMPLE_LANGUAGES)[number];

export type SampleSectionId = "personal" | "education" | "family" | "lifestyle";

export type SampleFieldKey =
	| "born"
	| "height"
	| "maritalStatus"
	| "motherTongue"
	| "languages"
	| "religion"
	| "education"
	| "university"
	| "profession"
	| "fatherOccupation"
	| "motherOccupation"
	| "siblings"
	| "familyType"
	| "nativePlace"
	| "diet"
	| "drinking";

/** The traditional order: Personal, Education & work, Family, Lifestyle, then About. */
export const SAMPLE_SECTIONS: ReadonlyArray<{ id: SampleSectionId; fields: SampleFieldKey[] }> = [
	{
		id: "personal",
		fields: ["born", "height", "maritalStatus", "motherTongue", "languages", "religion"],
	},
	{ id: "education", fields: ["education", "university", "profession"] },
	{
		id: "family",
		fields: ["fatherOccupation", "motherOccupation", "siblings", "familyType", "nativePlace"],
	},
	{ id: "lifestyle", fields: ["diet", "drinking"] },
];

export interface SamplePage {
	/** The language's own name, for the language row. */
	endonym: string;
	dir: "ltr" | "rtl";
	name: string;
	meta: string;
	signer: string;
	verified: string;
	veiled: string;
	veiledAlt: string;
	sections: Record<SampleSectionId | "about" | "sealed", string>;
	labels: Record<SampleFieldKey, string>;
	values: Record<SampleFieldKey, string>;
	about: string;
	sealedNote: string;
	sealedAria: string;
}

export const SAMPLE_PAGES: Record<SampleLanguage, SamplePage> = {
	en: {
		endonym: "English",
		dir: "ltr",
		name: "Arjun Mehta",
		meta: "31 · 5′ 11″ · Edison, New Jersey",
		signer: "Written by Arjun's parent, confirmed by Arjun",
		verified: "Verified email",
		veiled: "Veiled",
		veiledAlt: "Photo, veiled until you both say yes",
		sections: {
			personal: "Personal",
			education: "Education & work",
			family: "Family",
			lifestyle: "Lifestyle",
			about: "About",
			sealed: "Sealed",
		},
		labels: {
			born: "Born",
			height: "Height",
			maritalStatus: "Married before",
			motherTongue: "Mother tongue",
			languages: "Languages",
			religion: "Faith",
			education: "Education",
			university: "Studied at",
			profession: "Work",
			fatherOccupation: "Father",
			motherOccupation: "Mother",
			siblings: "Siblings",
			familyType: "Family",
			nativePlace: "Native place",
			diet: "Diet",
			drinking: "Drinking",
		},
		values: {
			born: "March 1995",
			height: "5′ 11″ (180 cm)",
			maritalStatus: "Never married",
			motherTongue: "Gujarati",
			languages: "English, Gujarati, Hindi",
			religion: "Hindu",
			education: "Master's degree",
			university: "Rutgers University",
			profession: "Software engineer",
			fatherOccupation: "Retired civil engineer",
			motherOccupation: "Schoolteacher",
			siblings: "One younger sister, married",
			familyType: "Nuclear family",
			nativePlace: "Vadodara, Gujarat",
			diet: "Vegetarian",
			drinking: "Occasionally",
		},
		about: "I build software for hospitals, cook for my parents on Sundays and play in a summer cricket league. I'd like to marry within a year, and I'm open to moving for the right person.",
		sealedNote: "Photos, full name, workplace and contact open when you both say yes.",
		sealedAria: "Sealed. Opens when you both say yes.",
	},
	hi: {
		endonym: "हिन्दी",
		dir: "ltr",
		name: "अर्जुन मेहता",
		meta: "31 · 5′ 11″ · एडिसन, न्यू जर्सी",
		signer: "अर्जुन के माता-पिता ने लिखा, अर्जुन ने पुष्टि की",
		verified: "ईमेल सत्यापित",
		veiled: "ढकी हुई",
		veiledAlt: "फ़ोटो ढकी हुई है, दोनों की हाँ के बाद खुलेगी",
		sections: {
			personal: "व्यक्तिगत",
			education: "शिक्षा और काम",
			family: "परिवार",
			lifestyle: "जीवनशैली",
			about: "परिचय",
			sealed: "मुहरबंद",
		},
		labels: {
			born: "जन्म",
			height: "कद",
			maritalStatus: "पहले विवाह",
			motherTongue: "मातृभाषा",
			languages: "भाषाएँ",
			religion: "धर्म",
			education: "शिक्षा",
			university: "पढ़ाई",
			profession: "काम",
			fatherOccupation: "पिता",
			motherOccupation: "माता",
			siblings: "भाई-बहन",
			familyType: "परिवार",
			nativePlace: "मूल स्थान",
			diet: "खान-पान",
			drinking: "शराब",
		},
		values: {
			born: "मार्च 1995",
			height: "5′ 11″ (180 सेमी)",
			maritalStatus: "अविवाहित",
			motherTongue: "गुजराती",
			languages: "अंग्रेज़ी, गुजराती, हिंदी",
			religion: "हिंदू",
			education: "स्नातकोत्तर",
			university: "रटगर्स यूनिवर्सिटी",
			profession: "सॉफ़्टवेयर इंजीनियर",
			fatherOccupation: "सेवानिवृत्त सिविल इंजीनियर",
			motherOccupation: "स्कूल शिक्षिका",
			siblings: "एक छोटी बहन, विवाहित",
			familyType: "एकल परिवार",
			nativePlace: "वडोदरा, गुजरात",
			diet: "शाकाहारी",
			drinking: "कभी-कभी",
		},
		about: "मैं अस्पतालों के लिए सॉफ़्टवेयर बनाता हूँ, रविवार को माता-पिता के लिए खाना बनाता हूँ और गर्मियों में क्रिकेट लीग में खेलता हूँ। एक साल के भीतर विवाह करना चाहता हूँ, और सही व्यक्ति के लिए शहर बदलने को तैयार हूँ।",
		sealedNote: "फ़ोटो, पूरा नाम, कार्यस्थल और संपर्क दोनों की हाँ के बाद खुलेंगे।",
		sealedAria: "मुहरबंद। दोनों की हाँ के बाद खुलेगा।",
	},
	ur: {
		endonym: "اردو",
		dir: "rtl",
		name: "ارجن مہتا",
		meta: "31 · 5′ 11″ · ایڈیسن، نیو جرسی",
		signer: "ارجن کے والدین نے لکھا، ارجن نے تصدیق کی",
		verified: "ای میل کی تصدیق",
		veiled: "پردے میں",
		veiledAlt: "تصویر پردے میں ہے، دونوں کی ہاں کے بعد کھلے گی",
		sections: {
			personal: "ذاتی معلومات",
			education: "تعلیم اور کام",
			family: "خاندان",
			lifestyle: "طرزِ زندگی",
			about: "تعارف",
			sealed: "مہر بند",
		},
		labels: {
			born: "پیدائش",
			height: "قد",
			maritalStatus: "پہلے شادی",
			motherTongue: "مادری زبان",
			languages: "زبانیں",
			religion: "مذہب",
			education: "تعلیم",
			university: "تعلیم کہاں سے",
			profession: "کام",
			fatherOccupation: "والد",
			motherOccupation: "والدہ",
			siblings: "بہن بھائی",
			familyType: "خاندان",
			nativePlace: "آبائی علاقہ",
			diet: "خوراک",
			drinking: "شراب",
		},
		values: {
			born: "مارچ 1995",
			height: "5′ 11″ (180 سینٹی میٹر)",
			maritalStatus: "غیر شادی شدہ",
			motherTongue: "گجراتی",
			languages: "انگریزی، گجراتی، ہندی",
			religion: "ہندو",
			education: "ماسٹرز",
			university: "رٹگرز یونیورسٹی",
			profession: "سافٹ ویئر انجینئر",
			fatherOccupation: "ریٹائرڈ سول انجینئر",
			motherOccupation: "اسکول ٹیچر",
			siblings: "ایک چھوٹی بہن، شادی شدہ",
			familyType: "چھوٹا خاندان",
			nativePlace: "وڈودرا، گجرات",
			diet: "سبزی خور",
			drinking: "کبھی کبھار",
		},
		about: "میں اسپتالوں کے لیے سافٹ ویئر بناتا ہوں، اتوار کو والدین کے لیے کھانا پکاتا ہوں اور گرمیوں میں کرکٹ لیگ میں کھیلتا ہوں۔ ایک سال کے اندر شادی کرنا چاہتا ہوں، اور صحیح شخص کے لیے شہر بدلنے کو تیار ہوں۔",
		sealedNote: "تصاویر، پورا نام، ملازمت کی جگہ اور رابطہ دونوں کی ہاں کے بعد کھلیں گے۔",
		sealedAria: "مہر بند۔ دونوں کی ہاں کے بعد کھلے گا۔",
	},
	pa: {
		endonym: "ਪੰਜਾਬੀ",
		dir: "ltr",
		name: "ਅਰਜੁਨ ਮਹਿਤਾ",
		meta: "31 · 5′ 11″ · ਐਡੀਸਨ, ਨਿਊ ਜਰਸੀ",
		signer: "ਅਰਜੁਨ ਦੇ ਮਾਪਿਆਂ ਨੇ ਲਿਖਿਆ, ਅਰਜੁਨ ਨੇ ਪੁਸ਼ਟੀ ਕੀਤੀ",
		verified: "ਈਮੇਲ ਪ੍ਰਮਾਣਿਤ",
		veiled: "ਢਕੀ ਹੋਈ",
		veiledAlt: "ਫ਼ੋਟੋ ਢਕੀ ਹੋਈ ਹੈ, ਦੋਵਾਂ ਦੀ ਹਾਂ ਤੋਂ ਬਾਅਦ ਖੁੱਲ੍ਹੇਗੀ",
		sections: {
			personal: "ਨਿੱਜੀ",
			education: "ਪੜ੍ਹਾਈ ਅਤੇ ਕੰਮ",
			family: "ਪਰਿਵਾਰ",
			lifestyle: "ਰਹਿਣ-ਸਹਿਣ",
			about: "ਜਾਣ-ਪਛਾਣ",
			sealed: "ਮੋਹਰਬੰਦ",
		},
		labels: {
			born: "ਜਨਮ",
			height: "ਕੱਦ",
			maritalStatus: "ਪਹਿਲਾਂ ਵਿਆਹ",
			motherTongue: "ਮਾਂ-ਬੋਲੀ",
			languages: "ਭਾਸ਼ਾਵਾਂ",
			religion: "ਧਰਮ",
			education: "ਪੜ੍ਹਾਈ",
			university: "ਕਿੱਥੋਂ ਪੜ੍ਹੇ",
			profession: "ਕੰਮ",
			fatherOccupation: "ਪਿਤਾ",
			motherOccupation: "ਮਾਤਾ",
			siblings: "ਭੈਣ-ਭਰਾ",
			familyType: "ਪਰਿਵਾਰ",
			nativePlace: "ਜੱਦੀ ਥਾਂ",
			diet: "ਖਾਣ-ਪੀਣ",
			drinking: "ਸ਼ਰਾਬ",
		},
		values: {
			born: "ਮਾਰਚ 1995",
			height: "5′ 11″ (180 ਸੈ.ਮੀ.)",
			maritalStatus: "ਕੁਆਰੇ",
			motherTongue: "ਗੁਜਰਾਤੀ",
			languages: "ਅੰਗਰੇਜ਼ੀ, ਗੁਜਰਾਤੀ, ਹਿੰਦੀ",
			religion: "ਹਿੰਦੂ",
			education: "ਪੋਸਟ-ਗ੍ਰੈਜੂਏਟ",
			university: "ਰਟਗਰਜ਼ ਯੂਨੀਵਰਸਿਟੀ",
			profession: "ਸਾਫ਼ਟਵੇਅਰ ਇੰਜੀਨੀਅਰ",
			fatherOccupation: "ਸੇਵਾਮੁਕਤ ਸਿਵਲ ਇੰਜੀਨੀਅਰ",
			motherOccupation: "ਸਕੂਲ ਅਧਿਆਪਕਾ",
			siblings: "ਇੱਕ ਛੋਟੀ ਭੈਣ, ਵਿਆਹੀ ਹੋਈ",
			familyType: "ਛੋਟਾ ਪਰਿਵਾਰ",
			nativePlace: "ਵਡੋਦਰਾ, ਗੁਜਰਾਤ",
			diet: "ਸ਼ਾਕਾਹਾਰੀ",
			drinking: "ਕਦੇ-ਕਦੇ",
		},
		about: "ਮੈਂ ਹਸਪਤਾਲਾਂ ਲਈ ਸਾਫ਼ਟਵੇਅਰ ਬਣਾਉਂਦਾ ਹਾਂ, ਐਤਵਾਰ ਨੂੰ ਮਾਪਿਆਂ ਲਈ ਖਾਣਾ ਬਣਾਉਂਦਾ ਹਾਂ ਅਤੇ ਗਰਮੀਆਂ ਵਿੱਚ ਕ੍ਰਿਕਟ ਲੀਗ ਵਿੱਚ ਖੇਡਦਾ ਹਾਂ। ਇੱਕ ਸਾਲ ਦੇ ਅੰਦਰ ਵਿਆਹ ਕਰਨਾ ਚਾਹੁੰਦਾ ਹਾਂ, ਅਤੇ ਸਹੀ ਇਨਸਾਨ ਲਈ ਸ਼ਹਿਰ ਬਦਲਣ ਨੂੰ ਤਿਆਰ ਹਾਂ।",
		sealedNote: "ਫ਼ੋਟੋਆਂ, ਪੂਰਾ ਨਾਮ, ਕੰਮ ਦੀ ਥਾਂ ਅਤੇ ਸੰਪਰਕ ਦੋਵਾਂ ਦੀ ਹਾਂ ਤੋਂ ਬਾਅਦ ਖੁੱਲ੍ਹਣਗੇ।",
		sealedAria: "ਮੋਹਰਬੰਦ। ਦੋਵਾਂ ਦੀ ਹਾਂ ਤੋਂ ਬਾਅਦ ਖੁੱਲ੍ਹੇਗਾ।",
	},
	gu: {
		endonym: "ગુજરાતી",
		dir: "ltr",
		name: "અર્જુન મહેતા",
		meta: "31 · 5′ 11″ · એડિસન, ન્યૂ જર્સી",
		signer: "અર્જુનના માતા-પિતાએ લખ્યું, અર્જુને પુષ્ટિ કરી",
		verified: "ઈમેલ ચકાસાયેલ",
		veiled: "ઢાંકેલો",
		veiledAlt: "ફોટો ઢાંકેલો છે, બંનેની હા પછી ખુલશે",
		sections: {
			personal: "અંગત",
			education: "અભ્યાસ અને કામ",
			family: "કુટુંબ",
			lifestyle: "જીવનશૈલી",
			about: "પરિચય",
			sealed: "મહોરબંધ",
		},
		labels: {
			born: "જન્મ",
			height: "ઊંચાઈ",
			maritalStatus: "અગાઉ લગ્ન",
			motherTongue: "માતૃભાષા",
			languages: "ભાષાઓ",
			religion: "ધર્મ",
			education: "અભ્યાસ",
			university: "ક્યાંથી અભ્યાસ",
			profession: "કામ",
			fatherOccupation: "પિતા",
			motherOccupation: "માતા",
			siblings: "ભાઈ-બહેન",
			familyType: "કુટુંબ",
			nativePlace: "વતન",
			diet: "ખોરાક",
			drinking: "દારૂ",
		},
		values: {
			born: "માર્ચ 1995",
			height: "5′ 11″ (180 સે.મી.)",
			maritalStatus: "અપરિણીત",
			motherTongue: "ગુજરાતી",
			languages: "અંગ્રેજી, ગુજરાતી, હિન્દી",
			religion: "હિંદુ",
			education: "અનુસ્નાતક",
			university: "રટગર્સ યુનિવર્સિટી",
			profession: "સોફ્ટવેર એન્જિનિયર",
			fatherOccupation: "નિવૃત્ત સિવિલ એન્જિનિયર",
			motherOccupation: "શાળા શિક્ષિકા",
			siblings: "એક નાની બહેન, પરિણીત",
			familyType: "વિભક્ત કુટુંબ",
			nativePlace: "વડોદરા, ગુજરાત",
			diet: "શાકાહારી",
			drinking: "ક્યારેક",
		},
		about: "હું હોસ્પિટલો માટે સોફ્ટવેર બનાવું છું, રવિવારે માતા-પિતા માટે રસોઈ કરું છું અને ઉનાળામાં ક્રિકેટ લીગમાં રમું છું. એક વર્ષમાં લગ્ન કરવા ઇચ્છું છું, અને યોગ્ય વ્યક્તિ માટે શહેર બદલવા તૈયાર છું.",
		sealedNote: "ફોટા, પૂરું નામ, કામનું સ્થળ અને સંપર્ક બંનેની હા પછી ખુલશે.",
		sealedAria: "મહોરબંધ. બંનેની હા પછી ખુલશે.",
	},
	bn: {
		endonym: "বাংলা",
		dir: "ltr",
		name: "অর্জুন মেহতা",
		meta: "31 · 5′ 11″ · এডিসন, নিউ জার্সি",
		signer: "অর্জুনের বাবা-মা লিখেছেন, অর্জুন নিশ্চিত করেছেন",
		verified: "ইমেল যাচাই করা",
		veiled: "ঢাকা",
		veiledAlt: "ছবিটি ঢাকা, দুজনে হ্যাঁ বললে খুলবে",
		sections: {
			personal: "ব্যক্তিগত",
			education: "শিক্ষা ও কাজ",
			family: "পরিবার",
			lifestyle: "জীবনযাপন",
			about: "পরিচয়",
			sealed: "সিলমোহর করা",
		},
		labels: {
			born: "জন্ম",
			height: "উচ্চতা",
			maritalStatus: "আগে বিয়ে",
			motherTongue: "মাতৃভাষা",
			languages: "ভাষা",
			religion: "ধর্ম",
			education: "শিক্ষা",
			university: "কোথায় পড়াশোনা",
			profession: "কাজ",
			fatherOccupation: "বাবা",
			motherOccupation: "মা",
			siblings: "ভাইবোন",
			familyType: "পরিবার",
			nativePlace: "আদি বাড়ি",
			diet: "খাদ্যাভ্যাস",
			drinking: "মদ্যপান",
		},
		values: {
			born: "মার্চ 1995",
			height: "5′ 11″ (180 সেমি)",
			maritalStatus: "অবিবাহিত",
			motherTongue: "গুজরাটি",
			languages: "ইংরেজি, গুজরাটি, হিন্দি",
			religion: "হিন্দু",
			education: "স্নাতকোত্তর",
			university: "রাটগার্স বিশ্ববিদ্যালয়",
			profession: "সফটওয়্যার ইঞ্জিনিয়ার",
			fatherOccupation: "অবসরপ্রাপ্ত সিভিল ইঞ্জিনিয়ার",
			motherOccupation: "স্কুলশিক্ষিকা",
			siblings: "এক ছোট বোন, বিবাহিত",
			familyType: "একক পরিবার",
			nativePlace: "বড়োদরা, গুজরাট",
			diet: "নিরামিষ",
			drinking: "মাঝে মাঝে",
		},
		about: "আমি হাসপাতালের জন্য সফটওয়্যার তৈরি করি, রবিবার বাবা-মায়ের জন্য রান্না করি আর গ্রীষ্মে ক্রিকেট লিগে খেলি। এক বছরের মধ্যে বিয়ে করতে চাই, আর সঠিক মানুষের জন্য শহর বদলাতে রাজি।",
		sealedNote: "ছবি, পুরো নাম, কর্মস্থল ও যোগাযোগ দুজনে হ্যাঁ বললে খুলবে।",
		sealedAria: "সিলমোহর করা। দুজনে হ্যাঁ বললে খুলবে।",
	},
	ta: {
		endonym: "தமிழ்",
		dir: "ltr",
		name: "அர்ஜுன் மேத்தா",
		meta: "31 · 5′ 11″ · எடிசன், நியூ ஜெர்சி",
		signer: "அர்ஜுனின் பெற்றோர் எழுதியது, அர்ஜுன் உறுதிசெய்தார்",
		verified: "மின்னஞ்சல் சரிபார்க்கப்பட்டது",
		veiled: "மறைக்கப்பட்டது",
		veiledAlt: "புகைப்படம் மறைக்கப்பட்டுள்ளது, இருவரும் சம்மதித்த பின் திறக்கும்",
		sections: {
			personal: "தனிப்பட்ட விவரம்",
			education: "கல்வி மற்றும் பணி",
			family: "குடும்பம்",
			lifestyle: "வாழ்க்கை முறை",
			about: "அறிமுகம்",
			sealed: "முத்திரையிடப்பட்டது",
		},
		labels: {
			born: "பிறப்பு",
			height: "உயரம்",
			maritalStatus: "முன்பு திருமணம்",
			motherTongue: "தாய்மொழி",
			languages: "மொழிகள்",
			religion: "மதம்",
			education: "கல்வி",
			university: "படித்த இடம்",
			profession: "பணி",
			fatherOccupation: "தந்தை",
			motherOccupation: "தாய்",
			siblings: "உடன்பிறந்தோர்",
			familyType: "குடும்பம்",
			nativePlace: "சொந்த ஊர்",
			diet: "உணவுப் பழக்கம்",
			drinking: "மது",
		},
		values: {
			born: "மார்ச் 1995",
			height: "5′ 11″ (180 செ.மீ.)",
			maritalStatus: "திருமணம் ஆகாதவர்",
			motherTongue: "குஜராத்தி",
			languages: "ஆங்கிலம், குஜராத்தி, இந்தி",
			religion: "இந்து",
			education: "முதுநிலைப் பட்டம்",
			university: "ரட்கர்ஸ் பல்கலைக்கழகம்",
			profession: "மென்பொருள் பொறியாளர்",
			fatherOccupation: "ஓய்வுபெற்ற சிவில் பொறியாளர்",
			motherOccupation: "பள்ளி ஆசிரியை",
			siblings: "ஒரு தங்கை, திருமணமானவர்",
			familyType: "தனிக் குடும்பம்",
			nativePlace: "வடோதரா, குஜராத்",
			diet: "சைவம்",
			drinking: "எப்போதாவது",
		},
		about: "நான் மருத்துவமனைகளுக்கான மென்பொருளை உருவாக்குகிறேன், ஞாயிற்றுக்கிழமைகளில் பெற்றோருக்குச் சமைக்கிறேன், கோடையில் கிரிக்கெட் லீக்கில் விளையாடுகிறேன். ஒரு வருடத்திற்குள் திருமணம் செய்ய விரும்புகிறேன்; சரியான நபருக்காக ஊர் மாறவும் தயார்.",
		sealedNote: "புகைப்படங்கள், முழுப் பெயர், பணியிடம், தொடர்பு ஆகியவை இருவரும் சம்மதித்த பின் திறக்கும்.",
		sealedAria: "முத்திரையிடப்பட்டது. இருவரும் சம்மதித்த பின் திறக்கும்.",
	},
	te: {
		endonym: "తెలుగు",
		dir: "ltr",
		name: "అర్జున్ మెహతా",
		meta: "31 · 5′ 11″ · ఎడిసన్, న్యూ జెర్సీ",
		signer: "అర్జున్ తల్లిదండ్రులు రాశారు, అర్జున్ నిర్ధారించారు",
		verified: "ఈమెయిల్ ధృవీకరించబడింది",
		veiled: "కప్పబడింది",
		veiledAlt: "ఫోటో కప్పబడి ఉంది, ఇద్దరూ అంగీకరించాక తెరుచుకుంటుంది",
		sections: {
			personal: "వ్యక్తిగత వివరాలు",
			education: "చదువు మరియు ఉద్యోగం",
			family: "కుటుంబం",
			lifestyle: "జీవనశైలి",
			about: "పరిచయం",
			sealed: "ముద్ర వేసినది",
		},
		labels: {
			born: "జననం",
			height: "ఎత్తు",
			maritalStatus: "ఇంతకు ముందు వివాహం",
			motherTongue: "మాతృభాష",
			languages: "భాషలు",
			religion: "మతం",
			education: "చదువు",
			university: "చదివిన చోటు",
			profession: "ఉద్యోగం",
			fatherOccupation: "తండ్రి",
			motherOccupation: "తల్లి",
			siblings: "తోబుట్టువులు",
			familyType: "కుటుంబం",
			nativePlace: "స్వస్థలం",
			diet: "ఆహారం",
			drinking: "మద్యం",
		},
		values: {
			born: "మార్చి 1995",
			height: "5′ 11″ (180 సెం.మీ.)",
			maritalStatus: "అవివాహితులు",
			motherTongue: "గుజరాతీ",
			languages: "ఇంగ్లీష్, గుజరాతీ, హిందీ",
			religion: "హిందూ",
			education: "పీజీ",
			university: "రట్గర్స్ విశ్వవిద్యాలయం",
			profession: "సాఫ్ట్‌వేర్ ఇంజనీర్",
			fatherOccupation: "రిటైర్డ్ సివిల్ ఇంజనీర్",
			motherOccupation: "స్కూల్ టీచర్",
			siblings: "ఒక చెల్లెలు, వివాహితురాలు",
			familyType: "చిన్న కుటుంబం",
			nativePlace: "వడోదర, గుజరాత్",
			diet: "శాకాహారం",
			drinking: "అప్పుడప్పుడు",
		},
		about: "నేను ఆసుపత్రుల కోసం సాఫ్ట్‌వేర్ తయారు చేస్తాను, ఆదివారాల్లో అమ్మానాన్నల కోసం వంట చేస్తాను, వేసవిలో క్రికెట్ లీగ్‌లో ఆడతాను. ఏడాదిలోపు పెళ్లి చేసుకోవాలనుకుంటున్నాను; సరైన వ్యక్తి కోసం ఊరు మారడానికి సిద్ధం.",
		sealedNote: "ఫోటోలు, పూర్తి పేరు, పని చేసే చోటు, సంప్రదింపు వివరాలు ఇద్దరూ అంగీకరించాక తెరుచుకుంటాయి.",
		sealedAria: "ముద్ర వేసినది. ఇద్దరూ అంగీకరించాక తెరుచుకుంటుంది.",
	},
};

/**
 * The family link as a mother reads it (design.md §5.9), in Hindi: the watermark strip, the page
 * at 130%, the question and the three square buttons. The words match the family bundle.
 */
export const FAMILY_LINK_SAMPLE = {
	lang: "hi",
	strip: "अर्जुन ने माँ के साथ निजी रूप से साझा किया",
	until: "शुक्र 3 अक्टूबर तक खुला · आगे न भेजें",
	translated: "अनुवादित।",
	name: "अर्जुन मेहता",
	meta: "31 · एडिसन, न्यू जर्सी",
	section: "परिवार",
	fields: [
		{ label: "पिता", value: "सेवानिवृत्त सिविल इंजीनियर" },
		{ label: "मूल स्थान", value: "वडोदरा, गुजरात" },
	],
	question: "आपकी क्या राय है?",
	reactions: [
		{ kind: "proceed", label: "आगे बढ़ें" },
		{ kind: "lets_talk", label: "बात करते हैं" },
		{ kind: "not_for_us", label: "हमारे लिए नहीं" },
	],
} as const;
